### ISSUE TITLE
How to use ShopifyQL with Public App?

### ISSUE THREAD

**Issue by veed76** [Shopify/shopify-api-php#110]
Hi 
Using this package is it possible to query this SHOW sum(pageview_count) OVER month(timestamp) AS month statement?
If yes then how we can execute it programmatically?

Currently, I'm using this package: https://github.com/osiset/laravel-shopify, and using that package I'm trying like this way, But it throwing the error.

Example Code:

$response = $shop->api()->graph("SHOW sum(pageview_count) OVER month(timestamp) AS month");
dd($response);
Error: https://prnt.sc/2005osy

Can anyone help me with this?
Thank you.

**Comment by paulomarg** [comment]
Hi @veed76. I assume you're working on a report in the REST API? If that's the case, you can check out our [reference page](https://shopify.dev/api/admin-rest/2021-10/resources/report#[post]/admin/api/2021-10/reports.json), where we provide an example of how you can run a ShopifyQL query using this library.

Hope this helps!
