### ISSUE TITLE
Looking forward to support Payments Apps API reference?

### ISSUE THREAD

**Issue by jackwiy** [Shopify/shopify-api-php#119]
Currently, API calls are fixed and cannot be customized, using different API paths.

GraphQL endpoint
The Payments Apps API is available at a single GraphQL endpoint:

POST https://{shop_domain}/payments_apps/api/2021-10/graphql.json

Please check the screenshot.
<img width="992" alt="iShot2021-12-06 18 18 10" src="https://user-images.githubusercontent.com/5044378/144829253-1ada3c11-7dda-448e-b933-04bbc80729c1.png">

**Comment by vildanbina** [comment]
@shababcardinity can you show us (a piece of code) how you did that?
