### ISSUE TITLE
Can you please add example projects vanila php, codeigniter & laravel?

### ISSUE THREAD

**Issue by contactlutforrahman** [Shopify/shopify-api-php#126]
I'm trying to integrate the api with Codeigniter. While initializing, I'm stuck on SHOPIFY_APP_HOST_NAME and session.
I don't know what is the shopify app host name and where can I get it? 
what is the session file or path I should use as I'm using Codeigniter?

Context::initialize(
    $_ENV['SHOPIFY_API_KEY'],
    $_ENV['SHOPIFY_API_SECRET'],
    $_ENV['SHOPIFY_APP_SCOPES'],
    $_ENV['SHOPIFY_APP_HOST_NAME'], // what is the shopify app host name? where can I get it?
    new FileSessionStorage('/tmp/php_sessions'), // what is the session file or path I should use here?
    '2021-04',
    true,
    false,
);

Is it possible you create example projects for vanila PHP, Codeigniter & Laravel so that developers like me can work on the shopify api.

**Comment by connor11528** [comment]
This is an example Laravel app the Shopify team provides: https://github.com/Shopify/shopify-app-php
