### ISSUE TITLE
"psr/log": "^1.1",

### ISSUE THREAD

**Issue by sil2** [Shopify/shopify-api-php#161]
# Issue summary

Can you remove or update requirements of         "psr/log": "^1.1", ?
current psr/log version is 3!

**Comment by MagicLegend** [comment]
Bad idea, since `psr/log` `^2.0|^3.0` [requires PHP 8.0](https://packagist.org/packages/psr/log). Are there reasons beyond being newer to actually update? There is no security advisory for `^1.1` on packagist.

**Comment by sk29110** [comment]
I am getting this and not sure what to do with it for v3.0.0. Would you recommend stick with 2.0? Please advice. 

![image](https://user-images.githubusercontent.com/626182/181131291-010ea3e5-7279-4152-8022-1112308a80bc.png)
