### ISSUE TITLE
Loosen Guzzlehttp requirement to allow v6

### ISSUE THREAD

**Issue by MagicLegend** [Shopify/shopify-api-php#170]
## Overview/summary

I'd like to see the requirement for `guzzle/guzzlehttp` loosened to also allow v6, instead of `^7.0`. I have [forked the project](https://github.com/MagicLegend/shopify-php-api), and downgraded the package. All tests still succeed, so I'm assuming v6 is fully compatible with this package as well.

I also have loosened `doctrine/inflector` to allow v1, which also doesn't break the tests. This is a deeper dependency to two Magento packages as well.

## Motivation

Magento v2.4.3 uses Guzzlehttp v6, and upgrading Magento is simply not an option. In our case:
```
$ composer2 why guzzlehttp/guzzle
magento/ece-tools                                  2002.1.10   requires  guzzlehttp/guzzle (^6.3||^7.3)
magento/framework                                  103.0.3-p1  requires  guzzlehttp/guzzle (^6.3.3)
magento/module-catalog-sync-admin                  1.0.4       requires  guzzlehttp/guzzle (~6.0)
magento/module-product-recommendations-admin       3.0.4       requires  guzzlehttp/guzzle (~6.0)
magento/module-product-recommendations-sync-admin  1.0.1       requires  guzzlehttp/guzzle (~6.0)
magento/product-community-edition                  2.4.3-p1    requires  guzzlehttp/guzzle (^6.3.3)                                                                                                                                                        
magento/product-enterprise-edition                 2.4.3-p1    requires  guzzlehttp/guzzle (^6.3.3)        
magento/product-recommendations-admin              3.0.5       requires  guzzlehttp/guzzle (~6.0)
magento/services-connector                         1.2.0       requires  guzzlehttp/guzzle (6.*)
```

```
$ composer2 why doctrine/inflector
illuminate/support  v5.8.36  requires  doctrine/inflector (^1.1)
```

```
$ composer2 why illuminate/support
illuminate/config  v5.8.36  requires  illuminate/support (5.8.*)  
```

```
$ composer2 why illuminate/config
magento/ece-tools             2002.1.10  requires  illuminate/config (^5.5||^8.77)
magento/magento-cloud-docker  1.3.2      requires  illuminate/config (^5.5||^8.77)
```

Would be great if it'd be allowed to use both packages with a lower version for better compatability.

**Comment by MagicLegend** [comment]
@rafaelstz Yes, since I'm talking about the `guzzlehttp` requirement that this package has:

https://github.com/Shopify/shopify-api-php/blob/7a5b651d276c833101ebb7a43106e55b2e532581/composer.json#L40

Since it does not allow v6, it restricts compatability with Magento versions `<2.4.4`, as per the change in `guzzlehttp` requirement between those versions: https://github.com/magento/magento2/commit/308377987b63452620d1d837dd0f92995a239da9. I'm referring to Magento to show that this package is not compatible with `<2.4.4` for this reason. Reading it again I do understand where you're coming from though, I hope I've cleared it up.

Also see my fork of this package in which I fixed a bunch of issues, including this one: https://github.com/MagicLegend/shopify-php-api

**Comment by MagicLegend** [comment]
> Yeah, and why is it stale bot? Because Shopify doesn't reply ;)

**Comment by MagicLegend** [comment]
> Yeah, and why is it stale bot? Because Shopify doesn't reply ;)

**Comment by MagicLegend** [comment]
> Yeah, and why is it stale bot? Because Shopify doesn't reply ;)

**Comment by MagicLegend** [comment]
> Yeah, and why is it stale bot? Because Shopify doesn't reply ;)

**Comment by MagicLegend** [comment]
> Yeah, and why is it stale bot? Because Shopify doesn't reply ;)

**Comment by ZacharyDuBois** [comment]
Issue wouldn't be stale if Shopify would answer

**Comment by ZacharyDuBois** [comment]
![Giphy](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExa254MGpvODJiMDA4M2QzOXBpY2JlOWR3dHp6aWVjcHVidWxtMzVzOSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/IxLeSDtUaZRmSiyCTf/giphy.gif)

**Comment by fulldecent** [comment]
Recommending to close this issue.

Guzzle 6.x is now end-of-life. Source: https://github.com/guzzle/guzzle?tab=readme-ov-file#version-guidance

This Shopify repo is currently supported at the "please send PRs" level. Source: https://github.com/Shopify/shopify-api-php/issues/322#issuecomment-2042726897

Therefore, I think it is reasonable to understand the project's scope as not including depending on unsupported dependencies.
