### ISSUE TITLE
Make it possible to specify log file

### ISSUE THREAD

**Issue by bSushil** [Shopify/shopify-api-php#174]
https://github.com/Shopify/shopify-php-api/blob/0556edf274ceb83346533bd22b662d7622e58c66/src/Clients/Http.php#L275

Hi
I am using this package to integrate Shopify in one of my apps. I would prefer if it were possible to provide custom file (and path) for logging errors, maybe probably through Context object.

**Comment by MagicLegend** [comment]
I am too, and just not giving the last argument (thus it being `null`) works just fine for me.

**Comment by nicolasf-akeneo** [comment]
@MagicLegend  The file created is not a log, but a timestamp to check when the last log of a deprecated api method is sent.
Currently there is no way to disable it, or set the path.
It is created in the same folder as the Http class, which isn't great in a cloud context.
Anyway, in general we do not write in the vendor folder.
