### ISSUE TITLE
Error When Trying To Fetch Webhooks List

### ISSUE THREAD

**Issue by lakshkhamesra** [Shopify/shopify-api-php#239]
# Issue summary

Error when trying to fetch current webhooks.

## Expected behavior

It should have returned a JSON response containing a list of webhooks

## Actual behavior

we get this error:

`Fatal error: Uncaught TypeError: Argument 1 passed to Shopify\Utils::loadCurrentSession() must be of the type array, null given, called in /www/doc/www.example.com/www/script/index.php on line 45 and defined in /www/doc/www.example.com/www/script/vendor/shopify/shopify-api/src/Utils.php:158 Stack trace: #0 /www/doc/www.example.com/www/script/index.php(45): Shopify\Utils::loadCurrentSession(NULL, NULL, NULL) #1 {main} thrown in /www/doc/www.example.com/www/script/vendor/shopify/shopify-api/src/Utils.php on line 158`

## Steps to reproduce the problem

1. Include the library:
```
require("vendor/autoload.php");

use Shopify\Auth\FileSessionStorage;
use Shopify\Auth\Session;
use Shopify\Rest\Admin2022_10\Customer;
use Shopify\Rest\Admin2022_10\Webhookv2;
use Shopify\Utils;
```

2. Initialize:
```
Shopify\Context::initialize(
    'apiKey',
    'apiSecretKey',
    'read_analytics, read_assigned_fulfillment_orders, read_customers, read_draft_orders, read_merchant_managed_fulfillment_orders, read_order_edits, read_orders, read_script_tags, read_third_party_fulfillment_orders',
    'https://sozialstar.de/script/',
    new FileSessionStorage('/tmp/php_sessions'),
    '2022-10',
);
```
3. Request webhook list:
```
$this->test_session = Utils::loadCurrentSession(
    $requestHeaders,
    $requestCookies,
    $isOnline
);
Webhookv2::webhooks(
    $this->test_session, // Session
    [], // Url Ids
    [], // Params
);
```

**Comment by lakshkhamesra** [comment]
P.S.
You can view it live [here](https://sozialstar.de/script/).

**Comment by lakshkhamesra** [comment]
`$requestHeaders = array('api_version'=>'2022-10', 'X-Shopify-Access-Token'=>'mytokenhere');
$requestCookies = array();
$isOnline = true;`

Abose is the value of the 3 variables and I still get the following error:

`Fatal error: Uncaught Shopify\Exception\MissingArgumentException: Missing Authorization key in headers array in /www/doc/www.sozialstar.de/www/script/vendor/shopify/shopify-api/src/Auth/OAuth.php:226 Stack trace: #0 /www/doc/www.sozialstar.de/www/script/vendor/shopify/shopify-api/src/Utils.php(160): Shopify\Auth\OAuth::getCurrentSessionId(Array, Array, true) #1 /www/doc/www.sozialstar.de/www/script/shopifytest.php(29): Shopify\Utils::loadCurrentSession(Array, Array, true) #2 {main} thrown in /www/doc/www.sozialstar.de/www/script/vendor/shopify/shopify-api/src/Auth/OAuth.php on line 226`

**Comment by rafaelstz** [comment]
So the error changed, what's happening now is that you have access without valid authorization.
In that case, you can accept the request, get the `$request->query("shop")`, and redirect the user to your login page with the shop in the URL. 
If your customer already has the app installed, the login page will generate another valid authorization and redirect the customer to the app's page. If the customer doesn't have the app installed, an installation request must pop-up.

**Comment by lakshkhamesra** [comment]
This is not a public app, its my own private admin custom app for my own shopify store for my personal use. I don't want to redirect a user, I just want to subscribe to new webhook orders/create. By the way, thank you for your help so far I appreciate it. Could you tell me how I would proceed in this scenario?
