### ISSUE TITLE
Can we get some basic examples of usage?

### ISSUE THREAD

**Issue by bogdanoasa** [Shopify/shopify-api-php#246]
Is there any documentation of a fully working (initialization + auth + endpoint call) example of this SDK? 

This would really help starting projects.

**Comment by rafaelstz** [comment]
These steps are helpful to start with it @bogdanoasa 

- https://shopify.dev/docs/apps/getting-started/create
- https://shopify.dev/docs/apps/auth
- https://shopify.dev/docs/apps/tools
