### ISSUE TITLE
Different scopes

### ISSUE THREAD

**Issue by sebastianpisula** [Shopify/shopify-api-php#248]
I have an application that performs certain tasks. It requires the following permissions:

write_shipping
read_orders
write_orders
As the app develops and new plans with new functionalities are added, the application requires additional permissions:

write_content
However, when executing the code:
$session = Utils::loadOfflineSession('');
we will not get a session.
The problem arises from the fact that in Session::isValid(), we verify the scopes that are stored in the db with the scopes from the configuration file:
Context::$SCOPES->equals($this->scope)
Should these be related to each other and should this validation be performed?

**Comment by WilRyan** [comment]
Check your db schema. It maybe truncating the scopes when stored

**Comment by sebastianpisula** [comment]
No, everything is okay in the database. The issue only exists when the app is live and new functionality is created. For example:

1. I have an app that requires the "read_products" scope to save prices in the app's database. I have 100 merchants, and everything is working correctly. I have webhooks to read products via the API using an offline token.
2. I received a feature request from my merchants that they need to update the meta fields of products with the lowest price (which looks like Omnibus). I created new functionality and added the "write_products" scope.
3. When the new feature is deployed, the API with the offline token will stop working because the session is invalid. The database has the "read_products" scope, and the new scope is "read_products,write_products". The user will need to reauthorize the app, and I want it to work seamlessly without any problems.

**Comment by WilRyan** [comment]
ah yeah you may need to re-authorise (just my guess only been in shopify dev space for a week). I just thought it maybe related as I found a similar issue while in development where i found the db field was using was too small for all the permission. GLHF :)
