### ISSUE TITLE
Prompt for '{"errors":"Not Found"}' error when creates or updates an asset for a theme

### ISSUE THREAD

**Issue by wumahoo** [Shopify/shopify-api-php#261]
# Issue summary

Document
https://shopify.dev/docs/api/admin-rest/2023-04/resources/asset#put-themes-theme-id-assets

# Requirements

- [ ] php 8.1
- [ ] shopify/shopify-api 4.3

## Expected behavior

PUT  /admin/api/2023-04/themes/{themeId}/assets.json

payload

```json
{
    "asset": {
       "key": "templates/xxxxx.liquid",
       "value": "xxxxxx"
   }
}
```

**Comment by wumahoo** [comment]
@adilizm 

Starting with Admin API 2023-04, Asset resource PUT or DEL requests are restricted using the write_themes [access scope](https://shopify.dev/docs/api/usage/access-scopes). If an app that's distributed in the Shopify App Store needs to use Asset resource PUT or DEL requests, then it needs to be granted an exemption by Shopify to use the write_themes access scope

https://shopify.dev/docs/apps/online-store/other-integration-methods/asset

**Comment by hyaminh2303** [comment]
> I already have the write_themes, read_themes scopes and still getting them while updating theme assets
> 
> PUT https://test.myshopify.com/admin/api/2023-10/themes/127604883630/assets.json
> 
> ```json
> {
>     "errors": "Not Found"
> }
> ```
> 
> But If i use the older version `2023-01` then it works


Same issue here, it worked well when I reverted to API version '2023-01'

**Comment by somin-parate** [comment]
Is there any solution here?

**Comment by somin-parate** [comment]
@krisforkpoint  yes you need to fill out the form here and in public url need to write app still in development https://docs.google.com/forms/d/e/1FAIpQLSfZTB1vxFC5d1-GPdqYunWRGUoDcOheHQzfK2RoEFEHrknt5g/viewform

Once you submit that within 2-3 days they will approve your request and you can use the assets api.

**Comment by krisforkpoint** [comment]
Thank you @somin-parate, I will submit a request and see if Shopify approves it.
