### ISSUE TITLE
Error when saving Product that was fetched previously

### ISSUE THREAD

**Issue by gimmixAT** [Shopify/shopify-api-php#275]
# Issue summary

When I fetch a Product and try to change something and save it again I get an error that the title must not be empty.

The reason for that seems to be that the `Base` `save` function decides whether to use POST or PUT based on if there is an `id` in the diff data. But since the `id` is equal in the `originalState` and the current data it is removed and the save function decides to POST the diffed object which in my case is missing a title.

I created a local hot fix for my project by checking `originalState` instead.
```php
$method = !empty($this->originalState[static::$PRIMARY_KEY]) ? "put" : "post";
```

But that might not work as intended in all scenarios

**Comment by friendscottn** [comment]
This still seems like an issue to me. If you fetch a product using `Product::find()` then modify some values and call `saveAndUpdate()` you end up with a duplicated product up on Shopify for the reason described above.
