### ISSUE TITLE
Class "App\FileSessionStorage" not found

### ISSUE THREAD

**Issue by vkharche** [Shopify/shopify-api-php#288]
# Issue summary

Write a short description of the issue here ↓

my code are

 $this->shopify = Context::initialize(
            apiKey: Config('constants.shopify.apikey'),
            apiSecretKey: config('constants.shopify.apisecret'),
            hostName: Config('constants.shopify.shopurl'),
            scopes: ['write_products', 'read_products'],
            sessionStorage: new FileSessionStorage('/tmp/php_sessions'),
            apiVersion: '2023-04',
            isEmbeddedApp: false,
            isPrivateApp: true,
        );

## Expected behavior

What do you think should happen?

## Actual behavior

What actually happens?

Tip: include an error message (in a `<details></details>` tag) if your issue is related to an error

## Steps to reproduce the problem

1.
1.
1.

## Reduced test case

The best way to get your bug fixed is to provide a [reduced test case](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Reducing_testcases).

---

## Checklist

- [ ] I have described this issue in a way that is actionable (if possible)

**Comment by FutureFutureTo** [comment]
maybe this will help - you have to setup your own session storage class:

https://github.com/Shopify/shopify-api-php/blob/main/docs/issues.md#notes-on-session-handling
