### ISSUE TITLE
Constructor of Shopify\Auth\Scopes can't handle null

### ISSUE THREAD

**Issue by sarim** [Shopify/shopify-api-php#290]
# Issue summary

During **Auth Begin**, a session is created without any scope / accessToken etc.. set. So these fields are null. In this state if $session->isValid() is called, it results in a TypeError. 

Because isValid calls `Context::$SCOPES->equals($this->scope)`. 
Here `$this->scope` is null. 
`SCOPES->equals` calls `$scopes = new self($scopes);`.

And in the constructor of `Scopes`

https://github.com/Shopify/shopify-api-php/blob/d368eef93ebbe639b8ef0c7d0249a79c417fe910/src/Auth/Scopes.php#L19-L27

`is_string` returns false for null type, but this code assumes that is not string, then must be array and continues. Resulting in `array_map` call throwing a TypeError because it expects array, but null given.

## Expected behavior

What do you think should happen?

No PHP TypeError should happen.

## Actual behavior

What actually happens?

TypeError

<details>

```php
php > require_once 'vendor/autoload_runtime.php';
php > $s = new \Shopify\Auth\Scopes(null);
PHP Warning:  Uncaught TypeError: array_map(): Argument #2 ($array) must be of type array, null given in /home/******************************/vendor/shopify/shopify-api/src/Auth/Scopes.php:27
Stack trace:
#0 /home/******************************/vendor/shopify/shopify-api/src/Auth/Scopes.php(27): array_map()
#1 php shell code(1): Shopify\Auth\Scopes->__construct()
#2 {main}
  thrown in /home/******************************/vendor/shopify/shopify-api/src/Auth/Scopes.php on line 27
```

</details>

## Steps to reproduce the problem

1. `php -a`
1.
```php
require_once 'vendor/autoload_runtime.php';
$s = new \Shopify\Auth\Scopes(null);
```

## Reduced test case

The best way to get your bug fixed is to provide a [reduced test case](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Reducing_testcases).

---

## Checklist

- [x] I have described this issue in a way that is actionable (if possible)

# Possible Solution
```php
    public function __construct($scopes)
    {
        if (is_string($scopes)) {
            $scopesArray = explode(self::SCOPE_DELIMITER, $scopes);
        } else {
            $scopesArray = $scopes ?? [];
        }
```

Adding  `?? []` should fix it.  

Or `Session->isValid` shouldn't call `Context::$SCOPES->equals` if `$this->scope` is null.

**Comment by devhus** [comment]
No one fixed this issue yet ??

**Comment by sarim** [comment]
> No one fixed this issue yet ??

@devhus you can see I opened a pull request https://github.com/Shopify/shopify-api-php/pull/299 way back then. But didn't receive any response.
