### ISSUE TITLE
setcookie() is passed a null instead of 0/[] during OAuth Callback.

### ISSUE THREAD

**Issue by da-mask** [Shopify/shopify-api-php#291]
# Issue summary

Write a short description of the issue here ↓
When using the package for OAuth of an offline/not embedded app, the function OAUTH::callback() attempts to use `setcookie()` with a null value for `expires:`  parameter.

## Expected behavior

What do you think should happen?
Either a `0` or empty array `[]` should be passed in instead. We could either make sure expiration does not fallback to being null, or change the constructor of OAuthCookie to set its own value to `0` if null is passed in.

## Actual behavior

What actually happens?

setcookie(): Argument #3 ($expires_or_options) must be of type array|int, null given

## Steps to reproduce the problem

1.  `OAuth::begin(
            shop: $this->shop->url,
            redirectPath: $this->redirectUri,
            isOnline: false,
        );`
1. ` $session = OAuth::callback(
            cookies: $cookies,
            query: $get
        );
        $accessToken = $session->getAccessToken();`

---

## Checklist

- [x] I have described this issue in a way that is actionable (if possible)

**Comment by erika89** [comment]
Yes @da-mask , i saw the PR after commenting this. I manage to solve it by doing the same, and forgot to let you know hehe. 
Thanks a lot!!!!
