### ISSUE TITLE
Shopify\Exception\MissingArgumentException: Missing Authorization key in headers array in file 

### ISSUE THREAD

**Issue by greatkanedo** [Shopify/shopify-api-php#294]
# Issue summary

Write a short description of the issue here ↓
I  get an error 
Shopify\Exception\MissingArgumentException: Missing Authorization key in headers array in file D:\project\aicclaravel\vendor\shopify\shopify-api\src\Auth\OAuth.php on line 226

But when I change the Authorization param like this:

            Context::initialize(
                config('oauth.appKeyShopify'),
                config('oauth.appSecretShopify'),
                config('oauth.appSecretScopes'),
                config('oauth.appHostName'),
                new FileSessionStorage('../storage/framework/sessions')
            );

            $headers = [
                'Authorization' => $token['access_token'],
            ];

            $this->shopifySession = Utils::loadCurrentSession(
                $headers,
                request()->cookies->all(),
                true
            );

I get an new error:

Missing Bearer token in authorization header

But when I change this code like this:
            $headers = [
                'Authorization' => "Bearer {$token['access_token']}",
            ];

I get an new error:

Wrong number of segments

When I review the api source code, I see this:

        $tks = \explode('.', $jwt);
        if (\count($tks) !== 3) {
            throw new UnexpectedValueException('Wrong number of segments');
        }

"count($tks) !== 3" let me feel important, What param will be, only the hosts, So I change code like this:

            $headers = [
                'Authorization' => "Bearer {$token['shop_host']}",  // xxx..myshopify.com
            ];

I get new error like this:

Syntax error, malformed JSON

with vendor\firebase\php-jwt\src\JWT.php:517.

Help me, PLZ.

**Comment by PencilaPravya** [comment]
@greatkanedo Have you got the solution for this am facing same issue

**Comment by greatkanedo** [comment]
> @greatkanedo Have you got the solution for this am facing same issue

Sorry, I can't fix it. have a good day.

**Comment by greatkanedo** [comment]
@Sharifur  Sorry, I can't fix it. have a good day.
