### ISSUE TITLE
Need Support On First Steps Of Using PHP REST API Library

### ISSUE THREAD

**Issue by DjThossi** [Shopify/shopify-api-php#295]
Hello

I'm fairly new to coding agains Shopify REST API.

Until today I used a third party library to talk to shopify's REST API because I'm not able to get the original library up and running. Here the links I've read and followed.

- https://shopify.dev/docs/api/admin-rest
- https://shopify.dev/docs/apps/auth/admin-app-access-tokens
-- I tried the Curl REST Example and got this working as described in the docu.

Here is what I have in code
In composer.json I have `"shopify/shopify-api": "^5.1"` installed

Here the sample code, which is causing the error message
```php
<?php
declare(strict_types=1);
namespace ShopifyConnector\ShopifySdk\Request;

use Shopify\Rest\Admin2023_07\Product;
use Shopify\Utils;

class ProductTest
{
    public function getAll()
    {
        Context::initialize(
            'MY_API_ID_AS_SHOWN_IN_SHOPIFY_APP_ADMIN_SECTION',
            'SAME_TOKEN_AS_IN_CURL_EXAMPLE',
            ['read_products'],
            'MY_DEV_SHOP.myshopify.com',
            new FileSessionStorage(),
        );

        $requestHeaders = [
            'Content-Type' => 'application/json',
            'X-Shopify-Access-Token' => 'SAME_TOKEN_AS_IN_CURL_EXAMPLE',
        ];

        $requestCookies = [];
        $isOnline = true;

        $test_session = Utils::loadCurrentSession(
            $requestHeaders,
            $requestCookies,
            $isOnline
        );

        $p = Product::all(
            $test_session, // Session
        );

        var_dump($p);
        die();
    }
}
```

This code causes an `Shopify\Exception\MissingArgumentException` with this message
`Missing Authorization key in headers array`

I dug a bit deeper into the library and found that I should have provided an authorisation header with some kind of Bearer token?

Can someone help me, please? And tell me what I'm doing wrong and what I'm missing?

Just a bit background about the App I'm building: It is an self hosted PHP application which reads products and orders from shopify and uses these data to tell our own production team what what they should focus on.

Who can help, please?

Thanks in advance for the help provided.

**Comment by spetracco** [comment]
I struggled with this recently too, and it's not well-documented. For some reason, the PHP library appears to operate differently than the documentation. Try changing your headers as follows:

`$requestHeaders = [
	'api_version' => '2023-04',
	'Authorization' => "Bearer YOUR_TOKEN_HERE",
];`

Update the api_version to whatever version you are intending to use.

**Comment by rafaelstz** [comment]
Hey @DjThossi use `Utils::loadOfflineSession` instead `Utils::loadCurrentSession`.

**Comment by DjThossi** [comment]
@dsbakaev Thank you very much. This comment finally made it work.

Here my final solution, based on the example above.

```php
<?php
declare(strict_types=1);
namespace ShopifyConnector\ShopifySdk\Request;

use Shopify\ApiVersion;
use Shopify\Auth\FileSessionStorage;
use Shopify\Auth\Session;
use Shopify\Context;
use Shopify\Rest\Admin2023_07\Product;

class ProductTest
{
    public function getAll(): void
    {
        Context::initialize(
            apiKey: 'API_KEY',
            apiSecretKey: 'API_SECRET_KEY',
            scopes: ['read_products'],
            hostName: 'MY_DEV_SHOP.myshopify.com',
            sessionStorage: new FileSessionStorage(),
            apiVersion: ApiVersion::JULY_2023,
            isEmbeddedApp: false,
        );

        $test_session = new Session(
            id: 'NA',
            shop: 'MY_DEV_SHOP.myshopify.com',
            isOnline: false,
            state: 'NA'
        );
        $test_session->setAccessToken('ADMIN_API_ACCESS_TOKEN');

        $p = Product::all(
            $test_session, // Session
        );

        var_dump($p);
        die();
    }
}
```

Thanks again to everyone for the help and support. Now I can use this library and follow the examples on shopify developers pages.

Thank you

**Comment by achintha5** [comment]
Could some one please put an example here how to authenticate the App for the first time using the above PHP client library.
