### ISSUE TITLE
Not support psr/http-message :^2.0

### ISSUE THREAD

**Issue by brightjune** [Shopify/shopify-api-php#321]
My PHP Used psr/http-message: ^2.0 (https://packagist.org/packages/psr/http-message), 

When I run compser require shopify/shopify-api, only can install shopify-api version 4.3. 

![image](https://github.com/Shopify/shopify-api-php/assets/5484071/8efb8dfe-64b9-492b-9762-63a6c586cf99)

**Comment by happyclicker** [comment]
+1 for this. Using Laravel 10, requires psr/http-message 2.0

Problem 1
    - Root composer.json requires shopify/shopify-api ^5.3 -> satisfiable by shopify/shopify-api[v5.3.0].
    - shopify/shopify-api v5.3.0 requires psr/http-message ^1.0 -> found psr/http-message[1.0, 1.0.1, 1.1] but the package is fixed to 2.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

**Comment by jesseschutt** [comment]
I'm in the same situation as @happyclicker and need to use the upgraded version to stay compliant with the API deprecations listed in my API health dashboard. I need to upgrade to at least `2023-07` by April 1st, 2024. 

Thank you!
