### ISSUE TITLE
shopify REST Admin API Response header doesn't includes a URL("link") for the next page of results

### ISSUE THREAD

**Issue by shaogatalam** [Shopify/shopify-api-php#329]
According to the official shopify documentation , "https://shopify.dev/docs/api/usage/pagination-rest#make-a-request-for-paginated-data" there will be a link to the next page in the response header.

but in my practical scenario , theres no link available in the response header , am i missing something ?

` 
$productEndpoint = "https://".$this->shop."/admin/api/2024-01/products.json";
        $perPage = 20; // Set the desired number of products per page
      
        
        $allProducts = [];
        
        do {
            // Append query parameters for per_page and page
            $url = $productEndpoint."?limit=".$perPage;
            
            $ch = curl_init($url);
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
            curl_setopt($ch, CURLOPT_HTTPHEADER, [
                'Content-Type: application/json',
                'X-Shopify-Access-Token: ' . $this->accessToken,
            ]);
        
            $response = curl_exec($ch);
            $headers  = curl_getinfo($ch);
          
           
            $productDataArray   = json_decode($response, true);
            var_dump($headers);
            
            if (isset($productDataArray['products']) && sizeof($productDataArray['products']) > 0) {
            
                $allProducts = array_merge($allProducts, $productDataArray['products']);
            }else{
              break;
            }
            // Close the cURL connection
            curl_close($ch);
        
        } while (true);
`

**Comment by mattc321** [comment]
This is off topic as it doesn't relate to this library. The link header will be there IF another page is possible. You are probably not enumerating the response headers correctly. I would suggest posting your question on stackexchange.

This rest api in this library will return an HttpResponse implementation that you can call hasHeader() off of, among other ways.
