### ISSUE TITLE
Adding filter by inner nodes to queries in Admin GraphQl

### ISSUE THREAD

**Issue by LouNik1984** [Shopify/shopify-api-php#368]
## Overview

Currently, Shopify's GraphQL Admin API does not support filtering by inner nodes or nested fields directly in queries, so when trying to filter by nested fields, the API ignores the filter and returns all the results. 

The only workaround currently available is to call all the data (so use no filter) and the cycle through the results to filter the data needed. 

This, however, is a very poor solution when you have hundreds and hundreds of entities to cycle through. It would be much easier to filter the query directly by their inner nodes so to have only the results needed. 

## Type

- [ ] New feature
- [X] Changes to existing features

## Motivation

> What inspired this feature request? What problems were you facing?

I have been tasked of retrieving only the companies with a particular customer email assigned to them. 

The companies query is quite straightforward: 

`{
 companies (first:10) {
  edges {
   node {
    name
    contacts (first:2) {
     nodes {
      customer {
       email
      }
     }
    }
   }
  }
 }
}`

If I want to filter the companies by companies direct attribute (eg: name): 

`companies (first:10 query:"name:'MY COMPANY NAME'") {...}`

the filter works as expected, I get one result, which is the company data with the name written in the query filter. 

However, the query filter doesn't work if I try to filter the companies list by any inner node (eg: customer email):

`companies (first:10 query:"contacts.customer.email:'customer@email.com'") {...}`

 This query gets ignored, and I get the list of all the companies instead.  I have to get 600+ companies to get only the 3 or 4 that have the data that I need. 

...

### Area

Admin GraphQL

**Comment by matteodepalo** [comment]
Could you link to the thread?

**Comment by matteodepalo** [comment]
Thank you for providing the link. The response seems to be AI generated and doesn't even mention the repo in which you should open the question. In any case, this is not an issue for this repo, but rather it should be kept in the community.
