### ISSUE TITLE
5.8.0 is breaking the authenticated fetch, webhooks register and other things

### ISSUE THREAD

**Issue by tommypepsi** [Shopify/shopify-api-php#383]
# Issue summary

The new release suddenly broke our application after a deployment. Since it's a minor release it got updated automatically and our app's dashboard broke. Not sure if it's because we have a setup that's a bit dated but setting a fixed version to 5.7.0 fixes the issue, so it seems something changed in 5.8.0 that doesn't work with our setup.

Though, I just cloned a basic setup following the php template and the same error happens:
https://github.com/Shopify/shopify-app-template-php

## Expected behavior

Not to break stuff 😅

## Actual behavior

Authenticated fetches return a `401 Unauthorized` error, the register webhook in the auth callback returns this `JsonException` error:
<details>
    "class": "JsonException",
    "message": "Syntax error",
    "code": 4,
    "file": "C:\\Users\\***\\Documents\\Code\\Shopify\\Apps\\***\\web\\vendor\\shopify\\shopify-api\\src\\Clients\\HttpResponse.php:48",
    "trace": [
        "C:\\Users\\***\\Documents\\Code\\Shopify\\Apps\\***\\web\\vendor\\shopify\\shopify-api\\src\\Clients\\HttpResponse.php:48",
        "C:\\Users\\***\\Documents\\Code\\Shopify\\Apps\\***\\web\\vendor\\shopify\\shopify-api\\src\\Webhooks\\Registry.php:192",
        "C:\\Users\\***\\Documents\\Code\\Shopify\\Apps\\***\\web\\vendor\\shopify\\shopify-api\\src\\Webhooks\\Registry.php:102",
        "C:\\Users\\***\\Documents\\Code\\Shopify\\Apps\\***\\web\\routes\\web.php:156" (The line here is `$response = Registry::register('/api/webhooks', Topics::APP_UNINSTALLED, $shopUrl, $accessToken);`),
        "C:\\Users\\***\\Documents\\Code\\Shopify\\Apps\\***\\web\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php:237",
        "C:\\Users\\***\\Documents\\Code\\Shopify\\Apps\\***\\web\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Route.php:208",
        "C:\\Users\\***\\Documents\\Code\\Shopify\\Apps\\***\\web\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php:721",
        "C:\\Users\\***\\Documents\\Code\\Shopify\\Apps\\***\\web\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php:128",
        "C:\\Users\\***\\Documents\\Code\\Shopify\\Apps\\***\\web\\app\\Http\\Middleware\\CspHeader.php:34",
        "C:\\Users\\***\\Documents\\Code\\Shopify\\Apps\\***\\web\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php:167",
        "C:\\Users\\***\\Documents\\Code\\Shopify\\Apps\\***\\web\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\SubstituteBindings.php:50",
        "C:\\Users\\***\\Documents\\Code\\Shopify\\Apps\\***\\web\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php:167",
</details>

And if I remove the webhook register the auth loops until shopify show an error.

## Steps to reproduce the problem

1. Create a basic installation of the php template following the instructions here: https://github.com/Shopify/shopify-app-template-php
2. Try to run the project.

---

## Checklist

- [x] I have described this issue in a way that is actionable (if possible)

**Comment by dv-ahardy** [comment]
@lizkenyon We still experienced the issue after testing this with one of our apps this morning using the 5.8.1 release. Specifically this was during the authentication stage of loading the app in Shopify store admin but presumably other areas too.

**Comment by lizkenyon** [comment]
Hi @dv-ahardy 

I am sorry to hear this.

I wasn't able to reproduce the issue any longer on a fresh app with the PHP template. 

Could you double check in your composer.lock that the project is actually using 5.8.1.

And if it is could you provide some more details about the exact error you are seeing, and if possible code for reproduction.
